### ISSUE TITLE
can find tradfri gateway

### ISSUE THREAD

**Issue by TobiBu** [tim-hellhake/tradfri-adapter#14]
Hi Tim,

just got the tradfri gateway and tried your add-on.
I can't discover the gateway and the log files give this error:

`2021-09-19 21:36:44.960 ERROR  : Failed to toggle add-on tradfri-adapter
2021-09-19 21:36:44.964 ERROR  : Error: Checksum failed for file /home/pi/.webthings/addons/tradfri-adapter/node_modules/semver/package.json in add-on tradfri-adapter
    at find.fileSync.forEach (/home/pi/webthings/gateway/build/webpack:/src/addon-utils.js:215:1)
    at Array.forEach (<anonymous>)
    at loadManifestJson (/home/pi/webthings/gateway/build/webpack:/src/addon-utils.js:197:1)
    at Object.loadManifest (/home/pi/webthings/gateway/build/webpack:/src/addon-utils.js:303:1)
    at AddonManager.loadAddon (/home/pi/webthings/gateway/build/webpack:/src/addon-manager.js:630:1)
    at AddonManager.enableAddon (/home/pi/webthings/gateway/build/webpack:/src/addon-manager.js:604:1)`
 
What does this tell me?
shall I remove and reinstalll the add-on? Probably with a reboot of the webthings gateway?

And maybe a more general question: What is the benefit of pairing the tradfri gateway with the webthings gateway? Why not directly pairing the tradfri devices with the webthings gateway?

thanks a lot for your help.

**Comment by tim-hellhake** [comment]
> What does this tell me?

The gateway validates the checksums of every file of the adapter to ensure that nothing was modified.
Removing and reinstalling the adapter should fix the issue.

> And maybe a more general question: What is the benefit of pairing the tradfri gateway with the webthings gateway? Why not directly pairing the tradfri devices with the webthings gateway?

It depends on your requirements.
If you pair them directly to the gateway
1. You need some Zigbee stick for the pi
2. You need to pair all your devices again
3. You can no longer use other apps/systems that rely on the tradfri gateway

If that's no problem for you, you might as well pair them directly to the gateway.
